# Welcome to Jekyll!
#

# bundle exec jekyll serve -l -H localhost
# docker compose up

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Gwanho Kim"
title_separator          : "-"
name                     : &name "Gwanho Kim"
description              : &description "personal description"
url                      : "https://gwanho.com" # Prod
# url                      : "http://localhost:4000" # Dev
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "khkim6040.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  avatar           : "profile.png"
  name             : "Gwanho Kim"
  pronouns         : "He/Him"
  location         : "Seongnam, South Korea"
  employer         : "Naver Financial"
  email            : "khkim6040@gmail.com"
  cv               : "/contents/files/resume_en.pdf"
  cv_ko            : "/contents/files/resume_ko.pdf"
  github           : "khkim6040"
  soundcloud       : "ho0ou"
  blog             : "https://blog.naver.com/ho0ou"
  solvedac         : "https://solved.ac/profile/khkim6040"

# Site Settings
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
atom_feed:
  hide                   : true      # change to true to hide the RSS feed in the footer


# Social Sharing
og_image                 :  "profile.png" # Social media default site image


# Analytics
analytics:
  google:
    tracking_id          : "G-XK5VK9Q1MG"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
  - docs
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control the types of collections used by the template
collections:
  hobbies:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
      related: true
      lang: en
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _hobbies
  - scope:
      path: ""
      type: hobbies
    values:
      layout: single
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
